name: build-go-win-binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]


jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies and build
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: |
          .bin/parkrun-events
          .bin/parkrun-milestones
